# This docker-compose.yml file  is fully functional to evaluate DefectDojo
# in your local environment.
#
# Although Docker Compose is one of the supported installation methods to
# deploy a containerized DefectDojo in a production environment, the
# docker-compose.yml file is not intended for production use without first
# customizing it to your particular situation.
---
services:
  nginx:
    build:
      dockerfile: "Dockerfile.nginx-${DEFECT_DOJO_OS:-alpine-arm64}"

  uwsgi:
    build:
      dockerfile: "Dockerfile.django-${DEFECT_DOJO_OS:-alpine-arm64}"

  postgres:
    image: postgres:17.5-alpine@sha256:f325a29ec9deb7039c5f07761d77d79d537dac836ecd99f982f6ca5476724604

  redis:
    # Pinning to this version due to licensing constraints
    image: valkey/valkey:7-alpine@sha256:de8ef4175e751dc2e9ea6167b5da9bbe86bf9feb7c59ef9ad8d8dc1595ae4aa8
